/** @dealora/db — schema, repository, and tenant-isolated persistence. */
export type {
  User,
  UserRole,
  Workspace,
  WorkspaceMember,
  BusinessProfile,
  EntityId,
  DateTime,
  ValidationError,
  ValidationSeverity,
  Offer,
  OfferStatus,
  OfferPricing,
  PricingModel,
  Icp,
  Persona,
  Positioning,
  BrandVoice,
  Claim,
  ClaimStatus,
  ClaimCategory,
  RevenueGoal,
  RevenueGoalEvent,
  RevenueGoalMetric,
  RevenueGoalEconomics,
  RevenueGoalConstraints,
  RevenueGoalApprovalPolicy,
  RevenueGoalUnknown,
  RevenueGoalStatus,
  GoalCompleteness,
  GoalMetricKind,
  IsoDate,
  RevenuePlan,
  RevenuePlanStatus,
  PlanStatement,
  PlanStatementKind,
  PlanBasis,
  RevenuePlanApproval,
  RevenuePlanStrategies,
  RevenuePlanIcpStrategy,
  RevenuePlanBuyerStrategy,
  RevenuePlanBuyerTarget,
  RevenuePlanSourcingStrategy,
  RevenuePlanSignalStrategy,
  RevenuePlanSignal,
  RevenuePlanQualificationStrategy,
  RevenuePlanQualificationCriterion,
  RevenuePlanOutreachStrategy,
  RevenuePlanFollowUpStrategy,
  RevenuePlanMeetingStrategy,
  RevenuePlanCrmPolicy,
  RevenuePlanMeasurementPlan,
  RevenuePlanOptimizationPlan,
  RevenuePlanKpi,
  RevenuePlanOptimizationLever,
} from "./types.js";
export { toDateTime } from "./types.js";

export {
  COLUMNS,
  SCHEMA,
  tables,
  indexes,
  userTable,
  workspaceTable,
  workspaceMembersTable,
  businessProfilesTable,
  offerTable,
  icpTable,
  personaTable,
  positioningTable,
  brandVoiceTable,
  claimTable,
  revenueGoalTable,
  revenueGoalEventTable,
  revenuePlanTable,
  createTableSql,
  slugify,
  capString,
} from "./schema.js";

export {
  Store,
  store,
  db,
  newId,
  hashPassword,
  verifyPassword,
  DB_DIR,
  LATEST_SCHEMA_VERSION,
  emptyState,
  migrateState,
} from "./repository.js";
export type { StorageError, StorageErrorCode, DbState, CompleteDbState } from "./repository.js";
